# Generated by Django 6.0.4 on 2026-06-09 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='habitaciones/'),
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='numero_hab',
            field=models.IntegerField(unique=True),
        ),
    ]
